version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://cmpt373-1211-08.cmpt.sfu.ca:5000'
        gitlab_rails['gitlab_shell_ssh_port'] = 5001
    ports:
      - '5000:5000'
      - '5001:22'
    volumes:
      - gitlab_config:/etc/config
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
